
filter-run-always: &filter-run-always
  filters:
    tags:
      only: /.*/

filter-run-on-master-and-version-tag-only: &filter-run-on-master-and-version-tag-only
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

aliases:
  - &step-checkout
    checkout
  - &step-restore-cache 
    restore_cache:
      keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-
  - &step-install
    run: npm install
  - &step-save-cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}
  - &step-build
    run: npm run build
  
build-node-common: &common-build
  working_directory: ~/repo
  steps:
    - *step-checkout
    - *step-restore-cache
    - *step-install
    - *step-save-cache
    - *step-build
    - run:
        name: Testing
        command: npm run test

version: 2
jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16
    steps:
      - *step-checkout
      - *step-restore-cache
      - *step-install
      - *step-save-cache
      - *step-build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish Package
          command: npm publish

  build-node14:
    <<: *common-build
    docker:
      - image: circleci/node:14

  build-node16:
    <<: *common-build
    docker:
      - image: circleci/node:16

workflows:
  version: 2
  build_all:
    jobs:
      - build-node14:
          <<: *filter-run-always
      - build-node16:
          <<: *filter-run-always
      - deploy:
          requires:
            - build-node14
            - build-node16
          <<: *filter-run-on-master-and-version-tag-only
